---
title: "Untitled"
output: html_document
date: "2025-05-17"
---

```{r}
library(ggplot2)
library(dplyr)


df <- data.frame(
  scales = c("always", "attractive", "cold", "hard", "small", "some"),
  exp1 = c(0.89583333, 0.416666667, 0.52083333, 0.72916667, 0.5, 1),
  exp2 = c(0.89583333, 0.39583333, 0.3125, 0.75, 0.479166667, 0.916666667)
)


df$diff <- df$exp2 - df$exp1


df$scales_full <- c(
  "<sometimes, always>",
  "<attractive, stunning>",
  "<cool, cold>",
  "<hard, unsolvable>",
  "<small, tiny>",
  "<some, all>"
)


df$scales_full <- factor(df$scales_full, levels = c(
  "<sometimes, always>",
  "<some, all>",
  "<hard, unsolvable>",
  "<cool, cold>",
  "<attractive, stunning>",
  "<small, tiny>"
))


ggplot(df, aes(x = scales_full, y = diff)) +
  geom_bar(stat = "identity", fill = "#4682B4") +
  coord_flip() +
  labs(
    title = "Difference in SI Endorsement (Exp2 - Exp1)",
    x = "Scales",
    y = "Rate Difference"
  ) +
  theme_minimal() +
  theme(
    text = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )


ggsave("si_diff_plot.pdf", width = 7, height = 4)


```



```{r}

df <- data.frame(
  scales = c("always", "attractive", "cold", "hard", "small", "some"),
  exp3 = c(0.86, 0.2, 0.44, 0.68, 0.32, 0.76),
  exp4 = c(0.791666667, 0.6666667, 0.6875, 0.708333333, 0.64583333, 0.77083333)
)


df$diff <- df$exp4 - df$exp3


df$scales_full <- c(
  "<sometimes, always>",
  "<attractive, stunning>",
  "<cool, cold>",
  "<hard, unsolvable>",
  "<small, tiny>",
  "<some, all>"
)


df$scales_full <- factor(df$scales_full, levels = c(
  "<sometimes, always>",
  "<some, all>",
  "<hard, unsolvable>",
  "<cool, cold>",
  "<attractive, stunning>",
  "<small, tiny>"
))


ggplot(df, aes(x = scales_full, y = diff)) +
  geom_bar(stat = "identity", fill = "#4682B4") +
  coord_flip() +
  labs(
    title = "Difference in SI Endorsement (Exp4 - Exp3)",
    x = "Scales",
    y = "Rate Difference"
  ) +
  theme_minimal() +
  theme(
    text = element_text(size = 12),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )


ggsave("si_diff_exp4_exp3_plot.pdf", width = 7, height = 4)

```

